### ISSUE TITLE
Can someone tell me how to fix this?

### ISSUE THREAD

**Issue by Ni3zam** [dialtoneuk/syscrack-prototype#12] opened 2018-04-04 10:32 UTC
FILE

C:\xampp\htdocs\src\Application\Utilities\FileSystem.php at line 306
ERROR MESSAGE

mkdir(): No such file or directory
TRACE

#0 [internal function]: flight\Engine->handleError(2, 'mkdir(): No suc...', 'C:\\xampp\\htdocs...', 306, Array)
#1 C:\xampp\htdocs\src\Application\Utilities\FileSystem.php(306): mkdir('C:/xampp/htdocs...')
#2 C:\xampp\htdocs\src\Views\Pages\Developer.php(486): Framework\Application\Utilities\FileSystem::createDirectory('conf/database')
#3 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(196): Framework\Views\Pages\Developer->connectionCreatorProcess()
#4 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#5 C:\xampp\htdocs\vendor\mikecao\flight\flight\Engine.php(311): flight\core\Dispatcher::execute(Array, Array)
#6 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(196): flight\Engine->_start()
#7 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(142): flight\core\Dispatcher::invokeMethod(Array, Array)
#8 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(48): flight\core\Dispatcher::execute(Array, Array)
#9 C:\xampp\htdocs\vendor\mikecao\flight\flight\Engine.php(65): flight\core\Dispatcher->run('start', Array)
#10 C:\xampp\htdocs\vendor\mikecao\flight\flight\core\Dispatcher.php(196): flight\Engine->__call('start', Array)
#11 C:\xampp\htdocs\vendor\mikecao\flight\flight\Flight.php(77): flight\core\Dispatcher::invokeMethod(Array, Array)
#12 C:\xampp\htdocs\src\Application.php(99): Flight::__callStatic('start', Array)
#13 C:\xampp\htdocs\index.php(312): Framework\Application->runFlight()
#14 {main}

**Comment by BlackHawk94** [comment] 2018-04-04 14:32
what are you trying to do? add database?

**Comment by BlackHawk94** [comment] 2018-04-04 14:39
Change manually the config file at C:\xampp\htdocs\data\config\database\connection.json

**Comment by dialtoneuk** [comment] 2019-04-30 17:04
The issue is with where the connection file was located. It doesn't match up with what's stated in the settings. This issue is fixed in the latest patch.

**Closed by dialtoneuk** 2019-04-30 17:04 UTC
